-- Support multiple browser/device push subscriptions per user.
-- Safe to run after the original push_subscriptions table exists.

ALTER TABLE public.push_subscriptions
    ADD COLUMN IF NOT EXISTS endpoint text,
    ADD COLUMN IF NOT EXISTS device_id text,
    ADD COLUMN IF NOT EXISTS device_label text,
    ADD COLUMN IF NOT EXISTS user_agent text,
    ADD COLUMN IF NOT EXISTS last_seen_at timestamptz NOT NULL DEFAULT now();

-- Backfill endpoint metadata for subscriptions saved by the previous version.
UPDATE public.push_subscriptions
SET endpoint = subscription_json->>'endpoint'
WHERE endpoint IS NULL
  AND subscription_json IS NOT NULL
  AND jsonb_typeof(subscription_json) = 'object'
  AND subscription_json ? 'endpoint';

-- The previous browser code assumed one row per user. Remove a UNIQUE(user_id)
-- constraint if the project schema has one, so a user can register many devices.
DO $$
DECLARE
    item record;
BEGIN
    FOR item IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'public.push_subscriptions'::regclass
          AND contype = 'u'
          AND regexp_replace(pg_get_constraintdef(oid), '\s+', '', 'g') = 'UNIQUE(user_id)'
    LOOP
        EXECUTE format(
            'ALTER TABLE public.push_subscriptions DROP CONSTRAINT %I',
            item.conname
        );
    END LOOP;

    -- Also remove a standalone, single-column unique index on user_id, if any.
    FOR item IN
        SELECT idx.relname AS index_name
        FROM pg_index ind
        JOIN pg_class tbl ON tbl.oid = ind.indrelid
        JOIN pg_namespace ns ON ns.oid = tbl.relnamespace
        JOIN pg_class idx ON idx.oid = ind.indexrelid
        JOIN pg_attribute att
          ON att.attrelid = tbl.oid
         AND att.attname = 'user_id'
         AND att.attnum = ind.indkey[0]
        WHERE ns.nspname = 'public'
          AND tbl.relname = 'push_subscriptions'
          AND ind.indisunique
          AND NOT ind.indisprimary
          AND ind.indnkeyatts = 1
          AND NOT EXISTS (
              SELECT 1
              FROM pg_constraint c
              WHERE c.conindid = ind.indexrelid
          )
    LOOP
        EXECUTE format('DROP INDEX IF EXISTS public.%I', item.index_name);
    END LOOP;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS push_subscriptions_user_device_uidx
    ON public.push_subscriptions(user_id, device_id)
    WHERE device_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS push_subscriptions_user_endpoint_uidx
    ON public.push_subscriptions(user_id, endpoint)
    WHERE endpoint IS NOT NULL;

CREATE INDEX IF NOT EXISTS push_subscriptions_user_id_idx
    ON public.push_subscriptions(user_id);

-- Reset RLS policies for this table to ensure each signed-in user can manage
-- only their own subscriptions. The scraper uses the server-side secret key,
-- which bypasses RLS as intended.
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    policy_row record;
BEGIN
    FOR policy_row IN
        SELECT policyname
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'push_subscriptions'
    LOOP
        EXECUTE format(
            'DROP POLICY IF EXISTS %I ON public.push_subscriptions',
            policy_row.policyname
        );
    END LOOP;
END $$;

CREATE POLICY push_subscriptions_select_own
    ON public.push_subscriptions
    FOR SELECT TO authenticated
    USING ((SELECT auth.uid()) = user_id);

CREATE POLICY push_subscriptions_insert_own
    ON public.push_subscriptions
    FOR INSERT TO authenticated
    WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY push_subscriptions_update_own
    ON public.push_subscriptions
    FOR UPDATE TO authenticated
    USING ((SELECT auth.uid()) = user_id)
    WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY push_subscriptions_delete_own
    ON public.push_subscriptions
    FOR DELETE TO authenticated
    USING ((SELECT auth.uid()) = user_id);

-- Per-match, per-device delivery ledger. A successful browser is not sent the
-- same match again if another browser fails; only failed devices are retried.
CREATE TABLE IF NOT EXISTS public.match_push_deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id bigint NOT NULL
        REFERENCES public.matches(id) ON DELETE CASCADE,
    push_subscription_id bigint NOT NULL
        REFERENCES public.push_subscriptions(id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'sent', 'failed')),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    last_attempt_at timestamptz,
    sent_at timestamptz,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT match_push_deliveries_match_subscription_key
        UNIQUE (match_id, push_subscription_id)
);

CREATE INDEX IF NOT EXISTS match_push_deliveries_match_id_idx
    ON public.match_push_deliveries(match_id);

CREATE INDEX IF NOT EXISTS match_push_deliveries_subscription_id_idx
    ON public.match_push_deliveries(push_subscription_id);

-- No client policies are added to the delivery ledger: it is managed by the
-- server-side scraper only. RLS prevents authenticated browser clients from
-- reading or altering delivery records.
ALTER TABLE public.match_push_deliveries ENABLE ROW LEVEL SECURITY;
